# Site settings
# accessible in the templates via {{ site.myvariable }}.

email: hello@jessicalchang.com
location: San Jose, CA
phone: (646) 469-7942
title: Jessica Chang
description: Jessica L. Chang UX/UI designer based in San Jose, California (Bay Area/Silicon Valley)
name: Jessica Chang
author: Jessica Chang
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jessicalchang.com" # the base hostname & protocol for your site, e.g. http://example.com
keywords: "Jessica Chang,ux,ui,ux/ui designer,designer,design,ux designer,ui designer,web design,silicon valley,bay area,sf bay area,portfolio"
page_title_suffixed: true
functions_endpoint: 'https://us-central1-jessica-portfolio.cloudfunctions.net'

instagram: https://www.instagram.com/jessicalchang/
dribble: https://dribbble.com/jessicalchang
pinterest: https://www.pinterest.com/itsjlcx3/
linkedin: https://www.linkedin.com/in/jessicalchang/

social:
  name: Jessica Chang
  links:
    - https://www.instagram.com/jessicalchang/
    - https://dribbble.com/jessicalchang
    - https://www.pinterest.com/itsjlcx3/
    - https://www.linkedin.com/in/jessicalchang/

collections:
  projects:
    output: true

prototypePath: /prototypes/

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
      path: 'prototypes'
    values:
      sitemap: false

exclude:
  - README.md
  - LICENSE
  - '*.sh'
  - 'Gemfile*'
  - functions
  - firebase.json
  - build.log
