# Site settings
# accessible in the templates via {{ site.myvariable }}.

title: Jessica L. Chang UX/UI Design Portfolio
email: jessicalauren718@gmail.com
location: San Jose, CA
phone: (646) 469-7942
description: Jessica L. Chang UX/UI design portfolio, based in Bay Area/Silicon Valley
name: Jessica Chang
author: Jessica Chang
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jessicalchang.com" # the base hostname & protocol for your site, e.g. http://example.com
keywords: "Jessica Chang,portfolio,ux design,ui design,designer,design,web design,silicon valley,bay area,sf bay area"

instagram: https://www.instagram.com/jessicalchang/
dribble: https://dribbble.com/jessicalchang
pinterest: https://www.pinterest.com/itsjlcx3/
linkedin: https://www.linkedin.com/in/jessicalchang/

social:
  name: Jessica Chang
  links:
    - https://www.instagram.com/jessicalchang/
    - https://dribbble.com/jessicalchang
    - https://www.pinterest.com/itsjlcx3/
    - https://www.linkedin.com/in/jessicalchang/

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
