# Site settings
# accessible in the templates via {{ site.myvariable }}.

title: Jessica L. Chang Portfolio
email: jessicalauren718@gmail.com
location: San Jose, CA
phone: (646) 469-7942
description: excerpt for SEO
name: Jessica Chang
baseurl: "/jessicalchang.com" # the subpath of your site, e.g. /blog
url: "http://jessicalchang.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
# plugins:
